version: "3"

services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb_compose
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  webapi:
    build:
      context: ./backend/ProductApi
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongodb

volumes:
  mongodb-data: