version: "3"

services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb_product_app
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  backend:
    build:
      context: ./backend/ProductApi
      dockerfile: Dockerfile
    container_name: backend_product_app
    ports:
      - "8080:80"
    environment:
      - ProductDatabase__ConnectionString=mongodb://mongodb:27017
    # OR with .env file
    # env_file:
    #  - .env
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend/product-app
      dockerfile: Dockerfile
    container_name: frontend_product_app
    ports:
      - "3000:80"
    depends_on:
      - backend
      
volumes:
  mongodb-data: